Letter.create([{ sender_id: 88, to_country_id: 12, from_country_id: 43, user_owl_id: 470, content: "Hello wore that after because concise like much exaggerated into by that spluttered darn wanton gosh much roughly that giggled parrot less imperatively coincidentally reproachful leaned then far fussy dear clinic and ouch that squirrel human excellently stank husky far earthworm toward oh hippopotamus squirrel.", sent_date: Time.current - 172800, delivery_date: Time.current - 86400},

{ sender_id: 88, to_country_id: 49, from_country_id: 43, user_owl_id: 470, receiver_id: 460, content: "More exquisite honey dog bewitching uneasy a hence where boisterously sleekly according in along let salaciously angelfish before jeez hopefully various pointed sincerely this crane bat goodness in this echidna reproachful that ouch much changed.", sent_date: Time.current - 359200, delivery_date: Time.current - 172800, pick_up_date: Time.current - 86400},

{ sender_id: 471, to_country_id: 43, from_country_id: 162, user_owl_id: 471, receiver_id: 88, content: "Swinged and sewed gratefully the lighted one buffalo barked regally ouch until hence shortsighted successfully supremely far less flippant regarding salamander assentingly vengefully after hence parrot spurious more instead fruitlessly wedded numbly well seal foul unlike reined.Hello wore that after because concise like much exaggerated into by that spluttered darn wanton gosh much roughly that giggled parrot less imperatively coincidentally reproachful leaned then far fussy dear clinic and ouch that squirrel human excellently stank husky far earthworm toward oh hippopotamus squirrel.", sent_date: Time.current - 189200, delivery_date: Time.current - 172800, pick_up_date: Time.current - 86400},

{ sender_id: 88, to_country_id: 43, from_country_id: 187, user_owl_id: 471, content: "Slapped when pinched sewed gratefully the lighted one buffalo barked regally ouch until hence shortsighted successfully supremely far less flippant regarding salamander assentingly vengefully after hence parrot spurious more instead fruitlessly wedded numbly well seal foul unlike reined.Hello wore that after because concise like much exaggerated into by that spluttered darn wanton gosh much roughly that giggled parrot less imperatively coincidentally reproachful leaned then far fussy dear clinic and ouch that squirrel human excellently stank husky far earthworm toward oh hippopotamus squirrel.", sent_date: Time.current - 9200, delivery_date: Time.current - 800},

{ sender_id: 33, to_country_id: 43, from_country_id: 184, user_owl_id: 33, content: "Slapped when pinched sewed gratefully the lighted one buffalo barked regally ouch until hence shortsighted successfully supremely far less flippant regarding salamander assentingly vengefully after hence parrot spurious more instead fruitlessly wedded numbly well seal foul unlike reined.Hello wore that after because concise like much exaggerated into by that spluttered darn wanton gosh much roughly that giggled parrot less imperatively coincidentally reproachful leaned then far fussy dear clinic and ouch that squirrel human excellently stank husky far earthworm toward oh hippopotamus squirrel.", sent_date: Time.current - 11200, delivery_date: Time.current - 4000},

{ sender_id: 20, to_country_id: 43, from_country_id: 184, user_owl_id: 20, content: "Slapped when pinched sewed gratefully the lighted one buffalo barked regally ouch until hence shortsighted successfully supremely far less flippant regarding salamander assentingly vengefully after hence parrot spurious more instead fruitlessly wedded numbly well seal foul unlike reined.Hello wore that after because concise like much exaggerated into by that spluttered darn wanton gosh much roughly that giggled parrot less imperatively coincidentally reproachful leaned then far fussy dear clinic and ouch that squirrel human excellently stank husky far earthworm toward oh hippopotamus squirrel.", sent_date: Time.current - 7000, delivery_date: Time.current - 2300},

{ sender_id: 16, to_country_id: 43, from_country_id: 181, user_owl_id: 16, content: "Slapped when pinched sewed gratefully the lighted one buffalo barked regally ouch until hence shortsighted successfully supremely far less flippant regarding salamander assentingly vengefully after hence parrot spurious more instead fruitlessly wedded numbly well seal foul unlike reined.Hello wore that after because concise like much exaggerated into by that spluttered darn wanton gosh much roughly that giggled parrot less imperatively coincidentally reproachful leaned then far fussy dear clinic and ouch that squirrel human excellently stank husky far earthworm toward oh hippopotamus squirrel.", sent_date: Time.current - 2300, delivery_date: Time.current - 1600},

{ sender_id: 50, to_country_id: 43, from_country_id: 184, user_owl_id: 50, content: "Slapped when pinched sewed gratefully the lighted one buffalo barked regally ouch until hence shortsighted successfully supremely far less flippant regarding salamander assentingly vengefully after hence parrot spurious more instead fruitlessly wedded numbly well seal foul unlike reined.Hello wore that after because concise like much exaggerated into by that spluttered darn wanton gosh much roughly that giggled parrot less imperatively coincidentally reproachful leaned then far fussy dear clinic and ouch that squirrel human excellently stank husky far earthworm toward oh hippopotamus squirrel.", sent_date: Time.current - 9200, delivery_date: Time.current - 800},

{ sender_id: 35, to_country_id: 43, from_country_id: 1, user_owl_id: 35, content: "Slapped when pinched sewed gratefully the lighted one buffalo barked regally ouch until hence shortsighted successfully supremely far less flippant regarding salamander assentingly vengefully after hence parrot spurious more instead fruitlessly wedded numbly well seal foul unlike reined.Hello wore that after because concise like much exaggerated into by that spluttered darn wanton gosh much roughly that giggled parrot less imperatively coincidentally reproachful leaned then far fussy dear clinic and ouch that squirrel human excellently stank husky far earthworm toward oh hippopotamus squirrel.", sent_date: Time.current - 2000, delivery_date: Time.current - 10}])